'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '../../lib/supabase'
import { getTrainer } from '../../lib/trainers'

export default function Plans() {
  const router = useRouter()
  const [profile, setProfile] = useState(null)
  const [plans, setPlans] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const stored = localStorage.getItem('profile')
    if (!stored) { router.push('/'); return }
    const p = JSON.parse(stored)
    setProfile(p)
    loadPlans(p.id)
  }, [])

  async function loadPlans(profileId) {
    const { data } = await supabase
      .from('plans')
      .select('*')
      .eq('profile_id', profileId)
      .order('created_at', { ascending: false })

    setPlans(data || [])
    setLoading(false)
  }

  if (loading || !profile) {
    return (
      <div style={{ padding: 40, textAlign: 'center', color: '#2D5B3F' }}>Loading plans...</div>
    )
  }

  const trainer = getTrainer(profile.trainer)
  const activeWorkout = plans.find(p => p.type === 'workout' && p.active)
  const activeMeal = plans.find(p => p.type === 'meal' && p.active)

  return (
    <div style={{ padding: '18px 20px 0' }}>
      <div style={{ marginBottom: 20 }}>
        <h1 style={{ fontSize: 26, fontWeight: 800, letterSpacing: -0.8 }}>
          <span style={{ color: '#6EE7B7' }}>Fit</span>
          <span style={{ color: '#fff' }}>Coach</span>
          <span className="gradient-accent" style={{ fontSize: 13, fontWeight: 600, marginLeft: 6 }}>AI</span>
        </h1>
        <p style={{ fontSize: 12, color: '#2D5B3F', fontWeight: 500, marginTop: 3 }}>Your active programs</p>
      </div>

      {/* Active Workout */}
      {activeWorkout ? (
        <div className="glass" style={{ padding: 0, marginBottom: 14, overflow: 'hidden' }}>
          <div style={{ height: 3, background: 'linear-gradient(90deg, #10B981, #6EE7B7)' }} />
          <div style={{ padding: 20 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 }}>
              <div>
                <div style={{ fontSize: 16, fontWeight: 700, color: '#fff' }}>
                  🏋️ {activeWorkout.content?.name || 'Workout Plan'}
                </div>
                <div style={{ fontSize: 12, color: '#2D5B3F', marginTop: 2 }}>
                  Generated by {trainer.name} · {activeWorkout.content?.daysPerWeek || '?'} days/week
                </div>
              </div>
              <div style={{
                fontSize: 10, fontWeight: 700, padding: '4px 10px', borderRadius: 100,
                background: 'rgba(110,231,183,0.1)', color: '#6EE7B7',
                border: '1px solid rgba(110,231,183,0.15)',
              }}>ACTIVE</div>
            </div>

            {/* Weekly split */}
            {activeWorkout.content?.split && (
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                {activeWorkout.content.split.map((day, i) => (
                  <div key={i} style={{
                    padding: '8px 14px', borderRadius: 10,
                    background: 'rgba(110,231,183,0.06)',
                    border: '1px solid rgba(110,231,183,0.08)',
                    fontSize: 12, fontWeight: 600, color: '#6EE7B7',
                  }}>{day}</div>
                ))}
              </div>
            )}

            {/* Full workout details */}
            {activeWorkout.content?.days && activeWorkout.content.days.map((day, dayIdx) => (
              <div key={dayIdx} style={{ marginTop: 16 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: '#6EE7B7', marginBottom: 8 }}>
                  {day.name}
                </div>
                {day.exercises && day.exercises.map((ex, i) => (
                  <div key={i} style={{
                    display: 'flex', justifyContent: 'space-between',
                    padding: '8px 0',
                    borderBottom: '1px solid rgba(110,231,183,0.04)',
                    fontSize: 13,
                  }}>
                    <span style={{ color: '#D1FAE5' }}>{ex.name}</span>
                    <span style={{ color: '#6EE7B7', fontWeight: 600 }}>{ex.sets}</span>
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="glass" style={{ padding: 24, textAlign: 'center', marginBottom: 14 }}>
          <div style={{ fontSize: 32, marginBottom: 8 }}>🏋️</div>
          <div style={{ color: '#2D5B3F', fontSize: 14 }}>No workout plan yet</div>
          <div style={{ color: '#1F4030', fontSize: 12, marginTop: 4 }}>Generate one from your dashboard</div>
        </div>
      )}

      {/* Active Meal Plan */}
      {activeMeal ? (
        <div className="glass" style={{ padding: 0, marginBottom: 14, overflow: 'hidden' }}>
          <div style={{ height: 3, background: 'linear-gradient(90deg, #F97316, #FBBF24)' }} />
          <div style={{ padding: 20 }}>
            <div style={{ fontSize: 16, fontWeight: 700, color: '#fff', marginBottom: 4 }}>
              🥗 {activeMeal.content?.name || 'Meal Plan'}
            </div>
            <div style={{ fontSize: 12, color: '#2D5B3F', marginBottom: 12 }}>
              {activeMeal.content?.dailyCalories} · {activeMeal.content?.protein} protein
            </div>

            {activeMeal.content?.meals && activeMeal.content.meals.map((meal, i) => (
              <div key={i} style={{
                display: 'flex', justifyContent: 'space-between',
                padding: '10px 0',
                borderTop: '1px solid rgba(110,231,183,0.04)',
              }}>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 600, color: '#D1FAE5' }}>{meal.name}</div>
                  <div style={{ fontSize: 11, color: '#1F4030' }}>{meal.description}</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: 13, fontWeight: 700, color: '#fff' }}>{meal.calories} cal</div>
                  <div className="gradient-accent" style={{ fontSize: 10, fontWeight: 600 }}>{meal.protein}g P</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="glass" style={{ padding: 24, textAlign: 'center', marginBottom: 14 }}>
          <div style={{ fontSize: 32, marginBottom: 8 }}>🥗</div>
          <div style={{ color: '#2D5B3F', fontSize: 14 }}>No meal plan yet</div>
          <div style={{ color: '#1F4030', fontSize: 12, marginTop: 4 }}>Generate one from your dashboard</div>
        </div>
      )}

      <button onClick={() => router.push('/dashboard')} style={{
        width: '100%', padding: 14, borderRadius: 14,
        border: '1px solid rgba(249,115,22,0.2)',
        background: 'linear-gradient(135deg, rgba(249,115,22,0.1), rgba(236,72,153,0.05))',
        color: '#FB923C', fontSize: 13, fontWeight: 700,
      }}>
        ↻ Regenerate plans from Dashboard
      </button>
    </div>
  )
}